---
- name: Obtener informacion de la maquina virtual
  community.vmware.vmware_guest_disk_info:
    hostname: '{{ lookup("env", "VMWARE_HOST") }}'
    username: '{{ lookup("env", "VMWARE_USER") }}'
    password: '{{ lookup("env", "VMWARE_PASSWORD") }}'
    validate_certs: 'no'
    datacenter: "{{ datacenter_name }}"
    name: "{{ vm_name }}"
  delegate_to: localhost
  register: disk_info

- name: Mostrar informacion de disco antes de modificar tamaño
  debug:
    msg: "{{ disk_info.guest_disk_info['0'].label }} este disco posee un espacio de {{ disk_info.guest_disk_info['0'].capacity_in_kb / 1024 }}"

- name: Expandir el disco de la maquina virtual
  community.vmware.vmware_guest_disk:
    hostname: '{{ lookup("env", "VMWARE_HOST") }}'
    username: '{{ lookup("env", "VMWARE_USER") }}'
    password: '{{ lookup("env", "VMWARE_PASSWORD") }}'
    validate_certs: 'no'
    datacenter: "{{ datacenter_name }}"
    name: "{{ vm_name }}"
    disk:
      - size_gb: "{{ new_disk_size_gb }}"
        unit_number: 0
        scsi_controller: 0
  delegate_to: localhost
  register: disk_modify

- name: Obtener tamaño de disco modificado
  community.vmware.vmware_guest_disk_info:
    hostname: '{{ lookup("env", "VMWARE_HOST") }}'
    username: '{{ lookup("env", "VMWARE_USER") }}'
    password: '{{ lookup("env", "VMWARE_PASSWORD") }}'
    validate_certs: 'no'
    datacenter: "{{ datacenter_name }}"
    name: "{{ vm_name }}"
  delegate_to: localhost
  register: disk_info_modify

- name: Mostrar informacion de disco despues de modificar tamaño
  debug:
    msg: "{{ disk_info_modify.guest_disk_info['0'].label }} este disco posee un espacio de {{ disk_info_modify.guest_disk_info['0'].capacity_in_kb / 1024 }} Mb"