---
- name: Reiniciar la VM
  reboot:
    reboot_timeout: 600
    test_command: whoami

- name: Esperar que el host esté accesible (SSH)
  wait_for_connection:
    timeout: 300

- name: Instalar gdisk (que incluye sgdisk)
  package:
    name: gdisk
    state: present

- name: Corregir la ubicación de la tabla secundaria GPT
  command: "sgdisk --move-second-header {{ disco_vm }}"

- name: Forzar el kernel a releer la tabla de particiones
  command: "partprobe {{ disco_vm }}"