---
- name: Reiniciar la maquina virtual para aplicar cambios
  reboot:
    reboot_timeout: 600
    test_command: whoami

- name: Esperar que el host esté accesible mediante ssh
  wait_for_connection:
    timeout: 300

- name: Instalar gdisk si es que no esta instalado
  package:
    name: gdisk
    state: present

- name: Corregir la ubicación de la tabla secundaria GPT
  command: "sgdisk --move-second-header {{ disco_vm }}"

- name: Forzar el kernel a releer la tabla de particiones
  command: "partprobe {{ disco_vm }}"