- name: Definir volúmenes con tamaños dinámicos
  set_fact:
    lvs:
      - { name: usr, size: "{{ size_usr }}g" }
      - { name: opt, size: "{{ size_opt }}g" }
      - { name: tmp, size: "{{ size_tmp }}g" }
      - { name: var, size: "{{ size_var }}g" }
      - { name: home, size: "{{ size_home }}g" }
      - { name: var_tmp, size: "{{ size_var_tmp }}g" }
      - { name: var_log, size: "{{ size_var_log }}g" }
      - { name: var_log_audit, size: "{{ size_var_audit }}g" }

- name: Ver espacio libre en el VG
  ansible.builtin.command: "vgs --noheadings --units g -o vg_name,vg_size,vg_free"
  register: vg_info

- name: Separar los valores del resultado de vgs
  set_fact:
    vg_campos: "{{ vg_info.stdout_lines[0].split() }}"

- name: Desactivar swap temporalmente
  ansible.builtin.command: "swapoff /dev/{{ vg_campos[0] }}/swap"

- name: Cambiar tamaño del volumen de swap
  community.general.lvol:
    vg: "{{ vg_campos[0] }}"
    lv: "swap"
    size: "{{ swap_size }}g"
    resizefs: false
    force: true
    state: present

- name: Formatear nuevamente el swap
  ansible.builtin.command: "mkswap /dev/{{ vg_campos[0] }}/swap"

- name: Activar de nuevo el swap
  ansible.builtin.command: "swapon /dev/{{ vg_campos[0] }}/swap"

- name: Modificar volumenes logicos o particiones
  community.general.lvol:
    vg: "{{ vg_campos[0] }}"
    lv: "{{ item.name }}"
    size: "{{ item.size }}"
    state: present
  loop: "{{ lvs }}"

- name: Expandir el volumen root con el espacio restante del vg
  community.general.lvol:
    vg: "{{ vg_campos[0] }}"
    lv: "root"
    size: "+100%FREE"
    resizefs: true
    state: present